name: pr hooks

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always


jobs:
  hooks:
    name: hooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Run pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files
