name: lint-test-cov

on:
  workflow_call:
    inputs:
      project_dir:
        description: "The directory of the project to lint & test"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always



jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  fmt:
    name: rust fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        run: cargo clippy -- -D warnings

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}
    container:
      image: xd009642/tarpaulin:develop-nightly
      options:  --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
